# Generated by Django 3.2.25 on 2024-09-16 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 9, 16, 19, 57, 30, 937110))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 9, 16, 19, 57, 30, 937110))),
            ],
        ),
    ]
